#!/bin/bash

# Quick Start Guide - Apache Airflow para Coleta de Dados FMI

echo "╔════════════════════════════════════════════════════════╗"
echo "║   GUIA RÁPIDO - Apache Airflow - Coleta Dados FMI     ║"
echo "╚════════════════════════════════════════════════════════╝"
echo ""
echo "📋 PASSO 1: Iniciar o Airflow"
echo "   ./start-airflow.sh"
echo ""
echo "📋 PASSO 2: Acessar Interface Web"
echo "   URL: http://localhost:8080"
echo "   Usuário: airflow"
echo "   Senha: airflow"
echo ""
echo "📋 PASSO 3: Ativar as DAGs"
echo "   Na interface web, ative o toggle das 4 DAGs:"
echo "   ✓ bop_data_collection"
echo "   ✓ er_data_collection"
echo "   ✓ iip_data_collection"
echo "   ✓ irfcl_data_collection"
echo ""
echo "📋 PASSO 4: Executar Manualmente (Opcional)"
echo "   Clique no botão ▶️ ao lado de cada DAG para executar imediatamente"
echo ""
echo "📅 AGENDAMENTO AUTOMÁTICO:"
echo "   • bop_data_collection    → 02:00 (diariamente)"
echo "   • er_data_collection     → 02:15 (diariamente)"
echo "   • iip_data_collection    → 02:30 (diariamente)"
echo "   • irfcl_data_collection  → 02:45 (diariamente)"
echo ""
echo "📁 RESULTADOS:"
echo "   Os arquivos CSV serão salvos em: ./Resultados/"
echo "   • BOP.csv"
echo "   • ER.csv"
echo "   • IIP.csv"
echo "   • IRFCL.csv"
echo ""
echo "🛑 PARAR O AIRFLOW:"
echo "   ./stop-airflow.sh"
echo ""
echo "📚 DOCUMENTAÇÃO COMPLETA:"
echo "   Veja AIRFLOW_README.md para mais detalhes"
echo ""
